version: "3"
services:
  app:
    image: twhatsappimage
    container_name: twhatsappcontainer
    build: ./
    restart: always
    ports: 
      - 3000:3000
      - 80:80
    environment:
      - PORT=3000
      - NODE_ENV=production



